# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/analytics_coffee_docs',
                'doc_host': 'https://cafe-com-analytics.github.io',
                'git_url': 'https://github.com/cafe-com-analytics/analytics_coffee_docs',
                'lib_path': 'analytics_coffee_docs'},
  'syms': {'analytics_coffee_docs\\core': {'analytics_coffee_docs\\core.foo': ('core.html#foo', 'analytics_coffee_docs\\core.py')}}}